### ISSUE TITLE
Config Initialisation

### ISSUE THREAD

**Issue by ffffionn** [superhawk610/multicast#33]
Whenever I run `node .config`, it gets an unexpected token error. I've only changed the mongo user/pass and Chromecast app ID.

{
  "appId": "XXXX1234",
  "mongoUser": "fionn",
  "mongoPass": "atestpassword",
  "mongoAuthSource": "admin",
  "mongoHost": "127.0.0.1",
  "mongoPort": 27017
}

Here's the full stack trace:

C:\dev\repos\multicast\.config:2
  "appId": "XXXX1234",
         ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by superhawk610** [comment]
```shell
node .config
```

is attempting to run the file `.config` as though it were a Node script. The command you're looking for is

```shell
multicast config
```

OR (note the space between `.` and `config`)

```shell
node . config
```

However, if you've already manually edited the `.config` file, this step is not necessary. You can get started by running

```shell
multicast start
```

OR

```shell
node .
```
