### ISSUE TITLE
Another error that causes multicast to crash often

### ISSUE THREAD

**Issue by plitewaikato** [superhawk610/multicast#42]
Recently I've begun getting this error after starting Multicast.  The whole service halts.  The Chromecasts continue to show the last content sent to them but I can't alter the content as I can't interact with the web environment.

`events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown
    at MDNSService.on_resolver_done (/usr/lib/node_modules/multicast/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/lib/node_modules/multicast/node_modules/mdns/lib/mdns_service.js:18:40)`

Any way I can just get multicast to ignore the error (whatever it is) and continue without halting?

**Comment by plitewaikato** [comment]
Nevermind, self inflicted injury.  I'm an idiot.  :)

**Comment by plitewaikato** [comment]
Turns out it's back again.

events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown
    at MDNSService.on_resolver_done (/usr/lib/node_modules/multicast/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/lib/node_modules/multicast/node_modules/mdns/lib/mdns_service.js:18:40)

When this occurs Multicast just falls over.  Relaunching it means it runs again for a few moments then dies once more.

**Comment by plitewaikato** [comment]
This might be the result of Avahi caching, adding this to the Avahi conf file seems to help

cache-entries-max=0

**Comment by superhawk610** [comment]
@plitewaikato has disabling Avahi caching solved the issue or just caused it to occur less often? What are your OS/system specs?

**Comment by plitewaikato** [comment]
Its been some help, but the crashes persist.  I'm running Debian on an
elderly laptop as the pilot, and if I can get it stable I'll roll it into
our VM infrastructure..

**Comment by superhawk610** [comment]
Any update on this? I'm not very well versed in Debian, so I may not be of much help here.

Out of curiosity, what version of Node and Multicast are you running?

**Comment by superhawk610** [comment]
Closing due to inactivity.
