### ISSUE TITLE
Error thrown in Devices Page: TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#6]
First, awesome project!

I'm running this on a headless Ubuntu system, and am having some difficulty actually getting the channels to push out to the devices.

Node Version: v6.11.4

Under the Devices page, when I try to click any of the buttons after registering a new Chromecast, I get the following error printed to the terminal, and nothing happens.

```
ocelotsloth@alpine:~/multicast$ node .
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
MultiCast is live!
listening at port 3944...
LAUNCH_ERROR
LAUNCH_ERROR
TypeError: Cannot read property 'emit' of undefined
    at app.get (/home/ocelotsloth/multicast/app/main.js:271:70)
    at Layer.handle [as handle_request] (/home/ocelotsloth/multicast/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ocelotsloth/multicast/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ocelotsloth/multicast/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ocelotsloth/multicast/node_modules/express/lib/router/layer.js:95:5)
    at /home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:281:22
    at param (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:354:14)
    at param (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:410:3)
    at next (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/ocelotsloth/multicast/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/ocelotsloth/multicast/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:317:13)
    at /home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ocelotsloth/multicast/node_modules/express/lib/router/index.js:275:10)
```

I'm going to be investigating this a bit on my own to try and better define the problem and try and work towards a solution, but I wanted to post the issue also for anyone else experiencing it.

**Comment by superhawk610** [comment]
In `app/main.js`, make the following change

```diff

- if (data.type != 'RECEIVER_STATUS') console.log(data.type)
+ if (data.type != 'RECEIVER_STATUS') {
+   console.log(data.type)
+   console.log(data)
+ }

```

then launch the app again

    node .

and post the log results.

**Comment by superhawk610** [comment]
Did you register the devices you're attempting to cast to via the Cast SDK console? Did you create your own application via the SDK console and use the application ID provided?

The `LAUNCH_ERROR` messages that you're seeing indicate that something went wrong when attempting to open the hub app on the receiver. This, in turn, means that the socket client was unable to connect from the receiver to the node server, and when the server attempts to emit a message to the receiver, it's not found. I'll need to add a try/catch or something similar to handle this error, nice catch.

**Comment by ocelotsloth** [comment]
Alright I failed to actually copy the application ID over to the config file. These errors make sense now.

Would it be easier to add a verification of some kind that ensures the given app ID is valid? That said, a try/catch would probably help with regressions.

**Comment by Brekmister** [comment]
ocelotsloth I think it's a good idea to make a setup script that does the configuration for you and double checks the app id.

**Comment by superhawk610** [comment]
This fix will be incorporated when wrapping as an NPM package (see #9).
