### ISSUE TITLE
Fails to assign channel to new Chromecast Device

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#7]
It's not actually throwing an error when I add the device, but it looks like when I try to add a new device, it doesn't actually assign the channel. It looks something like this:

![screen shot 2017-10-11 at 7 12 44 am](https://user-images.githubusercontent.com/9255772/31437597-ce2fd082-ae53-11e7-9fbb-bda66e281d07.png)

I've registered the "IT Office" Chromecast, but it does not say the name of the channel nor "no channel."

---

This causes an additional problem when you attempt to view the device page, as the Pug rendering expects there to be a value in the Channel position:

```
TypeError: /home/ocelotsloth/multicast/app/views/device.pug:35
    33|         option(selected, disabled, value='') Choose a Channel...
    34|         each c in channels
  > 35|           if device && device.channel && (c._id.toString() == device.channel._id.toString())
    36|             option(value=c._id, selected)= c.name
    37|           else
    38|             option(value=c._id)= c.name

Cannot read property 'toString' of undefined
    at eval (eval at wrap (/home/ocelotsloth/multicast/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:381:72)
    at eval (eval at wrap (/home/ocelotsloth/multicast/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:414:4)
    at template (eval at wrap (/home/ocelotsloth/multicast/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:924:72)
    at Object.exports.renderFile (/home/ocelotsloth/multicast/node_modules/pug/lib/index.js:428:38)
    at Object.exports.renderFile (/home/ocelotsloth/multicast/node_modules/pug/lib/index.js:418:21)
    at View.exports.__express [as engine] (/home/ocelotsloth/multicast/node_modules/pug/lib/index.js:465:11)
    at View.render (/home/ocelotsloth/multicast/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ocelotsloth/multicast/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/home/ocelotsloth/multicast/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ocelotsloth/multicast/node_modules/express/lib/response.js:1008:7)
    at Channel.find.sort.exec (/home/ocelotsloth/multicast/app/main.js:314:13)
    at /home/ocelotsloth/multicast/node_modules/mongoose/lib/query.js:3017:18
    at tryCatcher (/home/ocelotsloth/multicast/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ocelotsloth/multicast/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ocelotsloth/multicast/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ocelotsloth/multicast/node_modules/bluebird/js/release/promise.js:614:10)
```

Once in this state I have to drop the database and restart the app in order to do anything with that device.

**Comment by ocelotsloth** [comment]
Related to #6, this is the behavior when you don't give a valid application ID, as I just discovered.

**Comment by superhawk610** [comment]
This fix will be incorporated when wrapping as an NPM package (see #9).
